package control;

public enum Events {
	EDIT, DELETE, LOGIN, REGISTER, TOLOGIN, CONFIRM_REGISTER, ADD_FOLDER, ADD_FOLDER_INSIDE_OTHER,
	ADD_POSTAL, ADD_IMAGE, ADD_TEXT, CHANGE_HOST, VIEW_POSTAL, VIEW_IMAGE, VIEW_TEXT, SHOW_ADD_FOLDER,
	SHOW_ADD_FOLDER_INSIDE_OTHER, SHOW_ADD_POSTAL, SHOW_ADD_TEXT, SHOW_ADD_IMAGE, SHOW_EDIT, SHOW_EDIT_TEXT, EDIT_TEXT,
	SHOW_EDIT_IMAGE, EDIT_IMAGE, SHOW_DELETE, SHOW_VIEW_POSTAL, SHOW_VIEW_TEXT, SHOW_VIEW_IMAGE, POSTAL_SELECTED,
	IMAGE_SELECTED, TEXT_SELECTED, SHOW_ADD_USER, SHOW_CHANGE_PASSWORD, SHOW_CONCEDE_PRIVILEGES, ADD_USER,
	CHANGE_PASSWORD, CONCEDE_PRIVILEGES, RELOAD
}
