package modelsBatchMono;

public enum EnumSentence {
	
	 
	INTERRUPCION_IMPRIME_CONSOLA,DISPOSITIVOS_IMPRESORA,PROGRAMA, INTERRUPCION_VARIABLE_USER, INTERRUPCION_GET_HOUR,INTERRUPCION_APUNTADOR_MEMORY;
	
}
