-- MySQL Script generated by MySQL Workbench
-- Mon May 17 20:18:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema newProyectSoftware
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newProyectSoftware
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newProyectSoftware` DEFAULT CHARACTER SET utf8 ;
USE `newProyectSoftware` ;

-- -----------------------------------------------------
-- Table `newProyectSoftware`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newProyectSoftware`.`accounts` ;

CREATE TABLE IF NOT EXISTS `newProyectSoftware`.`accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NULL,
  `payment_value` INT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newProyectSoftware`.`persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newProyectSoftware`.`persons` ;

CREATE TABLE IF NOT EXISTS `newProyectSoftware`.`persons` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `fore_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` INT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`document_id`),
  INDEX `fk_person_accounts_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `newProyectSoftware`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newProyectSoftware`.`horizontal_propieties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newProyectSoftware`.`horizontal_propieties` ;

CREATE TABLE IF NOT EXISTS `newProyectSoftware`.`horizontal_propieties` (
  `horizontal_propiety_id` INT NOT NULL,
  `block` VARCHAR(1) NOT NULL,
  `number` INT NOT NULL,
  `persons_document_id` INT NOT NULL,
  PRIMARY KEY (`horizontal_propiety_id`),
  INDEX `fk_horizontal_propieties_persons1_idx` (`persons_document_id` ASC) VISIBLE,
  CONSTRAINT `fk_horizontal_propieties_persons1`
    FOREIGN KEY (`persons_document_id`)
    REFERENCES `newProyectSoftware`.`persons` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newProyectSoftware`.`bills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newProyectSoftware`.`bills` ;

CREATE TABLE IF NOT EXISTS `newProyectSoftware`.`bills` (
  `bill_id` INT NOT NULL AUTO_INCREMENT,
  `admin_number` INT NULL,
  `date_payment` DATE NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `payment_agreement` VARCHAR(45) NULL,
  `horizontal_propiety_id` INT NOT NULL,
  PRIMARY KEY (`bill_id`),
  INDEX `fk_bills_horizontal_propieties1_idx` (`horizontal_propiety_id` ASC) VISIBLE,
  CONSTRAINT `fk_bills_horizontal_propieties1`
    FOREIGN KEY (`horizontal_propiety_id`)
    REFERENCES `newProyectSoftware`.`horizontal_propieties` (`horizontal_propiety_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newProyectSoftware`.`details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newProyectSoftware`.`details` ;

CREATE TABLE IF NOT EXISTS `newProyectSoftware`.`details` (
  `detail_id` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `bill_id` INT NOT NULL,
  PRIMARY KEY (`detail_id`),
  INDEX `fk_details_bills1_idx` (`bill_id` ASC) VISIBLE,
  CONSTRAINT `fk_details_bills1`
    FOREIGN KEY (`bill_id`)
    REFERENCES `newProyectSoftware`.`bills` (`bill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newProyectSoftware`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newProyectSoftware`.`reservations` ;

CREATE TABLE IF NOT EXISTS `newProyectSoftware`.`reservations` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `reservation_date_start` DATETIME NOT NULL,
  `reservation_date_end` DATETIME NOT NULL,
  `reservation_type` VARCHAR(45) NOT NULL,
  `value` INT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `horizontal_propiety_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `fk_reservations_horizontal_propieties1_idx` (`horizontal_propiety_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_horizontal_propieties1`
    FOREIGN KEY (`horizontal_propiety_id`)
    REFERENCES `newProyectSoftware`.`horizontal_propieties` (`horizontal_propiety_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
