package network;

public enum Request {
	LOGIN, REGISTER, ADD_FOLDER, ADD_POSTAL, ADD_IMAGE, ADD_TEXT, ADD_FOLDER_INSIDE_OTHER, EDIT, EDIT_IMAGE, EDIT_TEXT,
	DELETE, VIEW_POSTAL, VIEW_IMAGE, VIEW_TEXT, GET_TREE_POSTAL_TO_USER, GET_TREE_USER, GET_IMAGE, GET_TEXT
}
